name: TopoReg
channels:
  - conda-forge
dependencies:
  - python == 3.8.16
  - numpy == 1.23.5
  - SciPy == 1.10.1
  - pandas == 1.5.0
  - scikit-learn == 1.2.2
  - networkx == 3.1
  - metric-learn == 0.6.2
  - matplotlib == 3.6.1
  - fastparquet == 2023.7.0
  - pip == 23.0.1
  - pip:
       - rdkit == 2023.9.1